default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: 123456
  host: localhost

development:
  <<: *default
  database: customer_x_development

test:
  <<: *default
  database: customer_x_test

production:
  <<: *default
  database: customer_x_production
  username: customer_x
  password: <%= ENV['CUSTOMER_X_DATABASE_PASSWORD'] %>
